default: build

build_qvm:
	$(MAKE) -C game build_qvm
	$(MAKE) -C cgame build_qvm
	$(MAKE) -C ui build_qvm

build_so:
	$(MAKE) -C game build_so
	$(MAKE) -C cgame build_so
	$(MAKE) -C ui build_so

clean:
	$(MAKE) -C game clean
	$(MAKE) -C cgame clean
	$(MAKE) -C ui clean
